language: python

python:
  - "3.4"

os:
  - osx

before_install:
  - brew update
  - brew install pyqt5 --with-python3

notifications:
  email:
    - julien@gns3.net
  #irc:
  #  channels:
  #    - "chat.freenode.net#gns3"
  #  on_success: change
  #  on_failure: always

install:
  - "pip install -r dev-requirements.txt"

script:
    - "py.test -vv"
